export const categories2 = [
  {
    id: 1,
    name: "Cake",
    image: require("../assets/images/Dessert/cakeIcon.png"),
  },
  {
    id: 2,
    name: "Ice Cream",
    image: require("../assets/images/Dessert/icecreamIcon.png"),
  },
  {
    id: 3,
    name: "Pudding",
    image: require("../assets/images/Dessert/puddingIcon.png"),
  },
  {
    id: 4,
    name: "Cookies",
    image: require("../assets/images/Dessert/cookiesIcon.png"),
  },
  {
    id: 5,
    name: "Milkshakes",
    image: require("../assets/images/Dessert/milkshakeIcon.png"),
  },
];

export const featured2 = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Piquant Palette",
      image: require("../assets/images/chocolatecakeDish.jpeg"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Chocolate Cake",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "White Sauce Pasta",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
    {
      id: 2,
      name: "Ambosia Alley",
      image: require("../assets/images/vanillaicecreamDish.jpeg"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Vanilla Ice Cream",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Culinary Restaurant",
      image: require("../assets/images/puddingDish.jpeg"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Caramel Pudding",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
    {
      id: 4,
      name: "Subway Restaurant",
      image: require("../assets/images/donutDish.jpeg"),
      description: "Hot and spicy pizzas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Donut",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaDish.png"),
        },
      ],
    },
  ],
};
